################################ 
##   2014-08-30 14:42:32.86   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
################################ 
##   2014-08-30 14:43:00.96   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
################################ 
##   2014-08-30 14:43:09.38   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
################################ 
##   2014-08-30 14:43:20.44   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
################################ 
##   2014-08-30 14:43:28.67   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
################################ 
##   2014-08-30 14:43:34.64   ## 
################################ 
 
Traceback (most recent call last):
  File ".\start.py", line 3, in <module>
    error
NameError: name 'error' is not defined
 
 
